### ISSUE TITLE
Output incorrectly aligned

### ISSUE THREAD

**Issue by simgar** [BartMassey-upstream/scip#1]
I've been using `scip` to establish that everything works with my 'RPi serial output to USB cable' setup.  Having configured both my Pi3 and my Pi4 to display messages on boot, I've run each multiple times and the output is great.  I love the way that everything appears to be exactly the same as on the Pi's monitor, even down to the colour-coding of the green `OK` message and the red 'busy' characters you see.  Nice job!

I've been using the command line:

    scip /dev/ttyUSB0 115200

and comparing it with:

    sudo python3 -m serial.tools.miniterm /dev/ttyUSB0 115200

For the RaspberryPi boot messages, `scip` is much better to look at.

So, then I moved to [rust-raspberrypi-OS-tutorials/05_drivers_gpio_uart](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/tree/master/05_drivers_gpio_uart)

When I use Python's `miniterm` with:

    sudo python3 -m serial.tools.miniterm /dev/ttyUSB0 921600

I get

	--- Miniterm on /dev/ttyUSB0  921600,8,N,1 ---
	--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
	[0] mingo version 0.5.0
	[1] Booting on: Raspberry Pi 3
	[2] Drivers loaded:
		  1. BCM PL011 UART
		  2. BCM GPIO
	[3] Chars written: 117
	[4] Echoing input now

When I use `scip` with: 

    scip /dev/ttyUSB0 921600

I get:

	Welcome to scip.
	To exit type <Enter> + ~ + .
	or unplug the serial port.
	[0] mingo version 0.5.0
						   [1] Booting on: Raspberry Pi 3
														 [2] Drivers loaded:
																				  1. BCM PL011 UART
						 2. BCM GPIO
									[3] Chars written: 117
														  [4] Echoing input now

Am I missing a parameter?

**Comment by BartMassey** [comment]
That's a bug in `mingo` (the Pi tutorial OS). It should be sending `\r\n` as a line ending on serial ports: this corresponds to "carriage return" (go to the beginning of the line) followed by "line feed" (go down to the next line). It instead just sends `\n`, leading to this behavior. There's a kludge in the `miniterm` provided with the tutorial to handle this, but the right way is to just fix the OS.

It's pretty easy to fix it yourself if you dig around in the `mingo` code. Otherwise, please be patient and we'll get the new setup with some fixes up as soon as we can find time.

**Comment by BartMassey** [comment]
I'm going to close this as not `scip`'s bug, but do please file a bug against <https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials>.
